export const TICKERS = [
  { symbol: 'SPY', name: 'S&P 500 ETF', group: 'Index' },
  { symbol: 'QQQ', name: 'Nasdaq 100 ETF', group: 'Index' },
  { symbol: 'DIA', name: 'Dow Jones ETF', group: 'Index' },
  { symbol: 'IWM', name: 'Russell 2000 ETF', group: 'Index' },
  { symbol: 'AAPL', name: 'Apple', group: 'Mega Cap' },
  { symbol: 'MSFT', name: 'Microsoft', group: 'Mega Cap' },
  { symbol: 'NVDA', name: 'NVIDIA', group: 'Mega Cap' },
  { symbol: 'AMZN', name: 'Amazon', group: 'Mega Cap' },
  { symbol: 'GOOGL', name: 'Alphabet', group: 'Mega Cap' },
  { symbol: 'META', name: 'Meta Platforms', group: 'Mega Cap' },
  { symbol: 'TSLA', name: 'Tesla', group: 'Mega Cap' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', group: 'Tech' },
  { symbol: 'NFLX', name: 'Netflix', group: 'Tech' },
  { symbol: 'CRM', name: 'Salesforce', group: 'Tech' },
  { symbol: 'JPM', name: 'JPMorgan Chase', group: 'Financials' },
  { symbol: 'BAC', name: 'Bank of America', group: 'Financials' },
  { symbol: 'XOM', name: 'Exxon Mobil', group: 'Energy' },
  { symbol: 'CVX', name: 'Chevron', group: 'Energy' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', group: 'Healthcare' },
  { symbol: 'UNH', name: 'UnitedHealth', group: 'Healthcare' },
  { symbol: 'BTC/USD', name: 'Bitcoin', group: 'Crypto' },
  { symbol: 'ETH/USD', name: 'Ethereum', group: 'Crypto' },
]
